### ISSUE TITLE
Why not set the value for $releasever in the description?

### ISSUE THREAD

**Issue by Sauraus** [chef-cookbooks/yum-centos#10]
```
default['yum']['base']['description'] = 'CentOS-$releasever - Base'
```
The above does not resolve to anything and just remains $releasever in the rendered .repo file is this intentional or a typo?

**Comment by someara** [comment]
$releasever (along with $arch, $basearch, $uuid) are variables used by yum internally.

http://linux.die.net/man/5/yum.conf

The description is just what's in the default files on a fresh centos install.
