### ISSUE TITLE
version constrain for yum

### ISSUE THREAD

**Issue by dzabel** [chef-cookbooks/yum-centos#21]
### Cookbook version
latest

### Chef-client version
12.x

### Platform Details
centos

introduced by this commit:
https://github.com/chef-cookbooks/yum-centos/commit/1f756bf2de89f5a2f28c62c2b23819aead5bdb55

version contrain for yum now uses 3 digits separated by points.
this lead to a downgrade of yum cookbook from 3.11.x to 3.10.x

please allow newer version of yum cookbook

**Comment by tas50** [comment]
This has been fixed in 0.4.13. Sorry for the strict constrain
