### ISSUE TITLE
Does this cookbook support setting and managing yum-priorities?

### ISSUE THREAD

**Issue by boldandbusted** [chef-cookbooks/yum-centos#25]
Thanks.

**Comment by iennae** [comment]
Not as currently written. As per the README **The yum-centos cookbook takes over management of the default repositoryids that ship with CentOS systems. It allows attribute manipulation of base, updates, extras, centosplus, contrib, and fasttrack**.

**Comment by boldandbusted** [comment]
I'd like to add that as a feature. Do you have any guidelines for adding feature to this cookbook? :) For me, it is the only aspect of yum configuration management that I really really miss.
