### ISSUE TITLE
Add support for multiple release vaults

### ISSUE THREAD

**Issue by nkadel** [chef-cookbooks/yum-centos#28]
### Cookbook version
3.0

### Chef-client version
14.1.12

### Platform Details
CentOS 7.5

### Scenario:
Provide yum access to previous CentOS 7.x releases from centos-vault

### Steps to Reproduce:
Find a package in the CentOS 7.0 release not found in CentOS 7.x, such as kernel-3.10.0-123.el7.x86_64. Look for it in any yum repository enabled by this cookbook For example, "yum list kernel-3.10.0-123.el7.x86_64 --enablerepo=*'

### Expected Result:
Packages installed from previous CentOS releases should be reported as present from previous vaults.

### Actual Result:
If the CentOS-Vault.repo has been successfully kept up-to-date, the package will be reported from there,  It will not be visible to this cookbook's published vaults.

The fix is to publish vault entries based on a hash of available CentOS releases, not on merely the current release.

**Comment by ramereth** [comment]
@nkadel can you please see how #36 works for you?
