### ISSUE TITLE
conflict with Software Collections repo

### ISSUE THREAD

**Issue by Wing924** [chef-cookbooks/yum-centos#29]
### Cookbook version
3.0.0

### Chef-client version
13.11.10

### Platform Details
CentOS 7

### Scenario:
```
package 'centos-release-SCL'
inlcude_recipe 'yum-centos'
```

### Steps to Reproduce:
run recipe

### Expected Result:
centos repo is deleted, but Software Collections repo exists

### Actual Result:
both centos and Software Collections repos are deleted

### Reason:
Software Collections repos are
```
CentOS-SCLo-scl-rh.repo
CentOS-SCLo-scl.repo
```
those code delete them:
https://github.com/chef-cookbooks/yum-centos/blob/master/recipes/default.rb#L36-L40

**Comment by scalp42** [comment]
Correct, opening a PR to prevent the deletions of SCL repos.

**Comment by scalp42** [comment]
@tas50 can close this issue ❤️
