### ISSUE TITLE
Broken compatibility with Chef <14 due to .delete_prefix use

### ISSUE THREAD

**Issue by Annih** [chef-cookbooks/yum-centos#42]
Hello,

With version *4.0.0* and *4.0.1* the compatibility with older Chef clients has been broken.
The `.delete_prefix` method has been added to the `::String` class in **ruby 2.5.0**, however Chef started to ship this version only in **14.0.0**.

I know version older than *14.0.0* are deprecated by Chef, but the current cookbook still advertise a **Chef 12.15** compatibility.

Should we fix the bug or change the Chef version support?

Thanks in advance.

**Comment by ramereth** [comment]
I'd rather we update the version it requires to 14. @tas50 will that be OK?

**Comment by tas50** [comment]
This seems like a pretty simple one to work around so we can maintain compatibility. The further back cookbooks support the easier upgrades to modern Chef Infra Client becomes.

**Comment by ramereth** [comment]
4.0.2 has been released which includes the fix.

**Comment by Annih** [comment]
Thank you @ramereth and @tas50 for this quick fix in addition to the "extended support" for Chef 12.
A significant amount of our server fleet is still running on that old Chef version, we hope to migrate them next quarter. 🤞
