### ISSUE TITLE
Do not delete CentOS-Vault.repo

### ISSUE THREAD

**Issue by nkadel** [chef-cookbooks/yum-centos#5]
Stop trying to delete CentOS-Vault.repo alone. It's very useful for environments that need to match packages with a slightly older deployed environment, or to use the "yum list extras" command on systems that have had 'centos-release' updated but not all other components.

**Comment by someara** [comment]
All default repositories shipped with the package are removed by convention.

The best thing to do here would be to add a attributes/vault.rb file that manages that channel in the same vein as extras, fasttrack, etc.
